# Generated by Django 2.2.6 on 2019-10-08 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronejob',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='cronejob',
            name='Url',
        ),
        migrations.AddField(
            model_name='cronejob',
            name='authentication',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='cronejob',
            name='password',
            field=models.CharField(default='', max_length=100, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='cronejob',
            name='title',
            field=models.CharField(default='', max_length=30, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='cronejob',
            name='url',
            field=models.CharField(default='', max_length=30, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='cronejob',
            name='username',
            field=models.CharField(default='', max_length=30, null='false'),
            preserve_default='false',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
